/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import Controller.Controller_KRSS;
import java.sql.Connection;
import koneksi.Database;


/**
 *
 * @author DELL
 */
public class frmKRS extends javax.swing.JFrame {
    Controller_KRSS controller;
    /**
     * Creates new form frmKRS
     */
    public frmKRS() {
        initComponents();
        setSize(1000,600);
        setVisible(true);
        controller = new Controller_KRSS(this);
        controller.reset();
    }
    public static void main(String args[]) {
       
    }
    public JButton getBtnBersih() {
        return btnBersih;
    }

    public JButton getBtnHapus() {
        return btnHapus;
    }

    public JButton getBtnSelesai() {
        return btnSelesai;
    }

    public JButton getBtnTambah() {
        return btnTambah;
    }

    public JComboBox<String> getCboSemester() {
        return cboSemester;
    }

    public JComboBox<String> getCboTA() {
        return cboTA;
    }

    public JTable getTblKRS() {
        return tblKRS;
    }

    public JTextField getTxtKodeMatakuliah() {
        return txtKodeMatakuliah;
    }

    public JTextField getTxtKodePrasyarat() {
        return txtKodePrasyarat;
    }

    public JTextField getTxtNIM() {
        return txtNIM;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtNamaMatakuliah() {
        return txtNamaMatakuliah;
    }

    public JTextField getTxtSKS() {
        return txtSKS;
    }

    public JTextField getTxtTglKRS() {
        return txtTglKRS;
    }

    public JTextField getTxtTotalSKS() {
        return txtTotalSKS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTA = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        cboTA = new javax.swing.JComboBox<>();
        cboSemester = new javax.swing.JComboBox<>();
        lblTglKRS = new javax.swing.JLabel();
        lblNIM = new javax.swing.JLabel();
        lblKodeMatakuliah = new javax.swing.JLabel();
        lblNamaMatakuliah = new javax.swing.JLabel();
        lblSKS = new javax.swing.JLabel();
        lblKodePrasyaratt = new javax.swing.JLabel();
        txtTglKRS = new javax.swing.JTextField();
        txtNIM = new javax.swing.JTextField();
        txtKodeMatakuliah = new javax.swing.JTextField();
        txtNamaMatakuliah = new javax.swing.JTextField();
        txtSKS = new javax.swing.JTextField();
        txtKodePrasyarat = new javax.swing.JTextField();
        lblTotalSKS = new javax.swing.JLabel();
        txtTotalSKS = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKRS = new javax.swing.JTable();
        txtNama = new javax.swing.JTextField();

        lblTA.setText("TA :");

        lblSemester.setText("Semester : ");

        cboTA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        cboTA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTAItemStateChanged(evt);
            }
        });
        cboTA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboTAFocusLost(evt);
            }
        });

        cboSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        cboSemester.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSemesterItemStateChanged(evt);
            }
        });
        cboSemester.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboSemesterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboSemesterFocusLost(evt);
            }
        });

        lblTglKRS.setText("Tanggal KRS");

        lblNIM.setText("NIM");

        lblKodeMatakuliah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKodeMatakuliah.setText("Kode Matakuliah :");

        lblNamaMatakuliah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaMatakuliah.setText("Nama Matakuliah");

        lblSKS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSKS.setText("SKS :");

        lblKodePrasyaratt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKodePrasyaratt.setText("Kode Prasyarat :");

        txtTglKRS.setEditable(false);
        txtTglKRS.setText("txtTglKRS");

        txtNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNIMFocusLost(evt);
            }
        });
        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });
        txtNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNIMKeyReleased(evt);
            }
        });

        txtKodeMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMatakuliahActionPerformed(evt);
            }
        });
        txtKodeMatakuliah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKodeMatakuliahKeyReleased(evt);
            }
        });

        txtNamaMatakuliah.setEditable(false);
        txtNamaMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMatakuliahActionPerformed(evt);
            }
        });

        txtSKS.setEditable(false);

        txtKodePrasyarat.setEditable(false);

        lblTotalSKS.setText("Total SKS : ");

        txtTotalSKS.setEditable(false);
        txtTotalSKS.setText("txtTotalSKS");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBersih.setText("Bersih");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        tblKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKRSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKRS);

        txtNama.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSemester)
                            .addComponent(lblTA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTglKRS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNIM)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNIM)
                            .addComponent(txtTglKRS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTotalSKS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSelesai))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtKodeMatakuliah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKodeMatakuliah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamaMatakuliah, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(txtNamaMatakuliah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSKS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSKS, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKodePrasyarat)
                                    .addComponent(lblKodePrasyaratt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBersih, btnHapus, btnTambah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTA)
                    .addComponent(cboTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTglKRS)
                    .addComponent(txtTglKRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(cboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNIM)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKodeMatakuliah)
                    .addComponent(lblNamaMatakuliah)
                    .addComponent(lblSKS)
                    .addComponent(lblKodePrasyaratt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodePrasyarat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnBersih)
                    .addComponent(btnSelesai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalSKS))
                .addContainerGap())
        );

        txtNamaMatakuliah.getAccessibleContext().setAccessibleName("");
        txtNamaMatakuliah.getAccessibleContext().setAccessibleDescription("");
        txtSKS.getAccessibleContext().setAccessibleName("");
        txtSKS.getAccessibleContext().setAccessibleDescription("");
        txtKodePrasyarat.getAccessibleContext().setAccessibleName("");
        txtKodePrasyarat.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMatakuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMatakuliahActionPerformed

    private void txtKodeMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMatakuliahActionPerformed
        // TODO add your handling code here:
        controller.tampilMatakuliah();
    }//GEN-LAST:event_txtKodeMatakuliahActionPerformed

    private void tblKRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKRSMouseClicked
        // TODO add your handling code here:
        controller.isiField(tblKRS.getSelectedRow());
    }//GEN-LAST:event_tblKRSMouseClicked

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        controller.reset();
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        controller.resetDetil();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.resetDetil();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        controller.insert();
        controller.resetDetil();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void cboSemesterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboSemesterFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSemesterFocusGained

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIMActionPerformed
        // TODO add your handling code here:
        controller.tampilNamaMahasiswa();
        controller.isiTabel();
    }//GEN-LAST:event_txtNIMActionPerformed

    private void cboTAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboTAFocusLost
        // TODO add your handling code here:
        controller.isiComboSemester();
        controller.isiTabel();
    }//GEN-LAST:event_cboTAFocusLost

    private void cboSemesterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboSemesterFocusLost
        // TODO add your handling code here:
        controller.isiTabel();
    }//GEN-LAST:event_cboSemesterFocusLost

    private void txtNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNIMFocusLost
        // TODO add your handling code here:
        controller.tampilNamaMahasiswa();
        controller.isiTabel();
    }//GEN-LAST:event_txtNIMFocusLost

    private void cboSemesterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSemesterItemStateChanged
        // TODO add your handling code here:
        controller.isiTabel();
    }//GEN-LAST:event_cboSemesterItemStateChanged

    private void cboTAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTAItemStateChanged
        // TODO add your handling code here:
        controller.isiComboSemester();
        controller.isiTabel();
    }//GEN-LAST:event_cboTAItemStateChanged

    private void txtNIMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIMKeyReleased
        // TODO add your handling code here:
        controller.tampilNamaMahasiswa();
        controller.isiTabel();
    }//GEN-LAST:event_txtNIMKeyReleased

    private void txtKodeMatakuliahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeMatakuliahKeyReleased
        // TODO add your handling code here:
        controller.tampilMatakuliah();
    }//GEN-LAST:event_txtKodeMatakuliahKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cboSemester;
    private javax.swing.JComboBox<String> cboTA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKodeMatakuliah;
    private javax.swing.JLabel lblKodePrasyaratt;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblNamaMatakuliah;
    private javax.swing.JLabel lblSKS;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTA;
    private javax.swing.JLabel lblTglKRS;
    private javax.swing.JLabel lblTotalSKS;
    private javax.swing.JTable tblKRS;
    private javax.swing.JTextField txtKodeMatakuliah;
    private javax.swing.JTextField txtKodePrasyarat;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaMatakuliah;
    private javax.swing.JTextField txtSKS;
    private javax.swing.JTextField txtTglKRS;
    private javax.swing.JTextField txtTotalSKS;
    // End of variables declaration//GEN-END:variables
}
