/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Color;
import koneksi.Database;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author edelweiss
 */
public class MenuAkademik extends javax.swing.JFrame {

    /**
     * Creates new form MenuAkademik
     */
    public MenuAkademik() {
        initComponents();
        setSize(1000,600);
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Connection  conn = Database.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuMahasiswa = new javax.swing.JMenuItem();
        mnuMatakuliah = new javax.swing.JMenuItem();
        mnuPeriode = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuKeluar = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        mnuKRSS = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        mnuCetakDaftarMahasiswa = new javax.swing.JMenuItem();
        mnuCetakDaftarMatakuliah = new javax.swing.JMenuItem();
        mnuCetakKRS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        mnuMahasiswa.setText("Entri Data Mahasiswa");
        mnuMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMahasiswaActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMahasiswa);

        mnuMatakuliah.setText("Entri Data Matakuliah");
        mnuMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMatakuliahActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMatakuliah);

        mnuPeriode.setText("Entri Data Periode");
        mnuPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPeriodeActionPerformed(evt);
            }
        });
        mnuFile.add(mnuPeriode);

        jMenuItem4.setText("Garis");
        mnuFile.add(jMenuItem4);

        mnuKeluar.setText("Keluar");
        mnuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuKeluar);

        jMenuBar1.add(mnuFile);

        mnuTransaksi.setText("Transaksi");
        mnuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTransaksiActionPerformed(evt);
            }
        });

        mnuKRSS.setText("Entri Data KRSS");
        mnuKRSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKRSSActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuKRSS);

        jMenuBar1.add(mnuTransaksi);

        Laporan.setText("Laporan");
        Laporan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                LaporanComponentHidden(evt);
            }
        });

        mnuCetakDaftarMahasiswa.setText("Cetak Daftar Mahasiswa");
        mnuCetakDaftarMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCetakDaftarMahasiswaActionPerformed(evt);
            }
        });
        Laporan.add(mnuCetakDaftarMahasiswa);

        mnuCetakDaftarMatakuliah.setText("Cetak Daftar Matakuliah");
        mnuCetakDaftarMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCetakDaftarMatakuliahActionPerformed(evt);
            }
        });
        Laporan.add(mnuCetakDaftarMatakuliah);

        mnuCetakKRS.setText("Cetak KRS");
        Laporan.add(mnuCetakKRS);

        jMenuBar1.add(Laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMahasiswaActionPerformed
        view.frmMahasiswa objMhs = new view.frmMahasiswa();
        objMhs.setLocationRelativeTo(this);
        objMhs.setVisible(true);
    }//GEN-LAST:event_mnuMahasiswaActionPerformed

    private void LaporanComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LaporanComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_LaporanComponentHidden

    private void mnuCetakDaftarMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCetakDaftarMatakuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCetakDaftarMatakuliahActionPerformed

    private void mnuMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMatakuliahActionPerformed
        view.frmMatakuliah objMtk = new view.frmMatakuliah();
        objMtk.setLocationRelativeTo(this);
        objMtk.setVisible(true);
    }//GEN-LAST:event_mnuMatakuliahActionPerformed

    private void mnuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuKeluarActionPerformed

    private void mnuPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPeriodeActionPerformed
        view.frmPeriode objPeriode = new view.frmPeriode();
        objPeriode.setLocationRelativeTo(this);
        objPeriode.setVisible(true);
    }//GEN-LAST:event_mnuPeriodeActionPerformed

    private void mnuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTransaksiActionPerformed
        // TODO add your handling code here:
  
        
    }//GEN-LAST:event_mnuTransaksiActionPerformed

    private void mnuKRSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKRSSActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        view.frmKRS krs = new view.frmKRS();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(krs,BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(1000,600);
        frame.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuKRSSActionPerformed

    private void mnuCetakDaftarMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCetakDaftarMahasiswaActionPerformed
        // TODO add your handling code here:
        view.FrmLapRemMhs objPeriode = new view.FrmLapRemMhs();
        objPeriode.setLocationRelativeTo(this);
        objPeriode.setVisible(true);
    }//GEN-LAST:event_mnuCetakDaftarMahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAkademik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mnuCetakDaftarMahasiswa;
    private javax.swing.JMenuItem mnuCetakDaftarMatakuliah;
    private javax.swing.JMenuItem mnuCetakKRS;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuKRSS;
    private javax.swing.JMenuItem mnuKeluar;
    private javax.swing.JMenuItem mnuMahasiswa;
    private javax.swing.JMenuItem mnuMatakuliah;
    private javax.swing.JMenuItem mnuPeriode;
    private javax.swing.JMenu mnuTransaksi;
    // End of variables declaration//GEN-END:variables
}
